#!/usr/bin/env python3
"""
*****************************************************************************
* A.R.M.O.R. - armor_project_tool.py
* Shared build, test, run and release-version workflow for A.R.M.O.R. repos.
* Copyright (C) 2026 JuanenRac (Electro Hobby 3D)
* GPL-3.0-or-later - see LICENSE
*****************************************************************************
"""
from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import time
import webbrowser
from datetime import date
from pathlib import Path


PYTHON_PROJECTS = {"ARMOR-COMMON", "ARMOR-SIMULATOR", "ARMOR-SERVER-AI", "ARMOR-VOICE-AI", "ARMOR-NETWORK"}
PYTEST_PROJECTS = {"ARMOR-UPDATER"}
NODE_PROJECTS = {"ARMOR-SERVER", "ARMOR-STUDIO"}
NPM = "npm.cmd" if os.name == "nt" else "npm"


def load_server_environment(project: Path, environment: dict[str, str]) -> dict[str, str]:
    """Load local server secrets, creating an ignored development file once.

    The API deliberately refuses empty credentials.  A first ``run`` must still
    be usable, so this function creates distinct high-entropy local values in
    ``.env`` when it does not exist.  The file is ignored by Git and values
    already supplied by the operating-system environment take precedence.
    """
    env_file = project / ".env"
    if not env_file.is_file():
        ingest = secrets.token_urlsafe(32)
        control = secrets.token_urlsafe(32)
        operator = secrets.token_urlsafe(32)
        camera_config_key = secrets.token_urlsafe(48)
        studio_password = secrets.token_urlsafe(24)
        env_file.write_text(
            "# Local development secrets. Generated by armor-project; do not commit.\n"
            "ARMOR_PORT=8080\n"
            f"ARMOR_INGEST_TOKEN={ingest}\n"
            f"ARMOR_CONTROL_TOKEN={control}\n"
            f"ARMOR_OPERATOR_TOKEN={operator}\n"
            f"ARMOR_CAMERA_CONFIG_KEY={camera_config_key}\n"
            "ARMOR_STUDIO_ORIGIN=http://127.0.0.1:5178\n"
            "ARMOR_STUDIO_USERNAME=admin\n"
            f"ARMOR_STUDIO_PASSWORD={studio_password}\n",
            encoding="utf-8",
        )
        print("ARMOR_LOCAL_SECRETS=CREATED .env (Git-ignored)")
    for line in env_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        # An inherited empty variable must not shadow the valid local value.
        # This happens easily after a failed manual command in cmd.exe.
        current = environment.get(key.strip(), "")
        if key and (not current or current.startswith("replace-with-")):
            environment[key.strip()] = value.strip()
    return environment


def command(project: Path, args: list[str], environment: dict[str, str] | None = None) -> None:
    print("$", " ".join(args), flush=True)
    try:
        result = subprocess.run(args, cwd=project, env=environment, check=False)
    except FileNotFoundError as error:
        raise RuntimeError(f"required executable was not found: {args[0]}") from error
    if result.returncode:
        raise RuntimeError(f"command failed with exit code {result.returncode}")


def check_tool(name: str, message: str) -> str:
    path = shutil.which(name)
    if not path:
        raise RuntimeError(message)
    return path


def test_project(project: Path, manifest: dict[str, object]) -> None:
    name = str(manifest["name"])
    if name in PYTHON_PROJECTS:
        environment = os.environ.copy()
        environment["PYTHONPATH"] = str(project / "src") + os.pathsep + environment.get("PYTHONPATH", "")
        command(project, [sys.executable, "-m", "unittest", "discover", "-s", "tests"], environment)
    elif name in PYTEST_PROJECTS:
        # A stdlib-only CLI/install core with an optional pytest-based test
        # suite and an optional PySide6 desktop shell - `pip install -e
        # ".[dev]"` first so `pytest` and the package's own console entry
        # point are both on PATH for this checkout.
        command(project, [sys.executable, "-m", "pip", "install", "-q", "-e", ".[dev]"])
        environment = os.environ.copy()
        environment["PYTHONPATH"] = str(project / "src") + os.pathsep + environment.get("PYTHONPATH", "")
        command(project, [sys.executable, "-m", "pytest", "tests", "-q"], environment)
    elif name in NODE_PROJECTS:
        check_tool("npm", "npm is required; install Node.js 22 or newer")
        # A fresh checkout (every CI run; a developer machine only the first
        # time) has no node_modules yet - found for real when ARMOR-SERVER's
        # and ARMOR-STUDIO's own CI runs failed with "Cannot find module"
        # for every import, because typecheck ran before anything installed
        # a single dependency. Reusing an existing tree (rather than
        # reinstalling unconditionally) matters on a developer machine,
        # where a running editor/linter can hold a native module's file
        # open.
        if not (project / "node_modules").is_dir():
            command(project, [NPM, "ci"])
        command(project, [NPM, "run", "typecheck"])
        command(project, [NPM, "test"])
        command(project, [NPM, "run", "build"])
    elif name == "ARMOR-RADAR":
        test_radar(project)
    elif name == "ARMOR-SOLAR":
        test_solar(project)
    elif name == "ARMOR-ELECTRICAL":
        test_electrical(project)
    elif name == "ARMOR-ANDROID-CONTROL":
        gradle = "gradlew.bat" if os.name == "nt" and (project / "gradlew.bat").is_file() else ("./gradlew" if (project / "gradlew").is_file() else check_tool("gradle", "Gradle or the project wrapper is required; open the project in Android Studio once to generate/restore it"))
        command(project, [gradle, "test", "assembleDebug"])
    elif name == "ARMOR-HARDWARE":
        openscad = check_tool("openscad", "OpenSCAD is required to validate the parametric enclosure")
        output = project / "build" / "node_enclosure.stl"
        output.parent.mkdir(exist_ok=True)
        command(project, [openscad, "-o", str(output), "scad/node_enclosure.scad"])
    elif name == "ARMOR-DEVOPS":
        check_tool("docker", "Docker Compose is required to validate ARMOR-DEVOPS")
        # `docker compose config` only checks the topology is well formed; it
        # still needs every variable the compose file interpolates to have
        # SOME value. generate_secrets.sh's own real, disposable secrets are
        # exactly that - CI never reuses them past this one validation run.
        if not (project / ".env").is_file():
            command(project, ["bash", "scripts/generate_secrets.sh"])
        command(project, ["docker", "compose", "config", "--quiet"])
    elif name == "ARMOR-DOCS":
        validate_markdown_links(project)
    else:
        raise RuntimeError(f"no build rule registered for {name}")


def test_radar(project: Path) -> None:
    """Build and run the hardware-independent core on this computer, then the firmware if ESP-IDF is present.

    The host tests need CMake and a C++17 compiler (Linux, macOS, WSL or MSYS2). The firmware image itself
    needs ESP-IDF; without it the run says so instead of pretending the image was built.
    """
    cmake = check_tool("cmake", "CMake and a C++17 compiler are required to test ARMOR-RADAR's core (use Linux, WSL or MSYS2)")
    build = project / "build" / "host"
    command(project, [cmake, "-S", "tests", "-B", str(build), "-DCMAKE_BUILD_TYPE=Debug"])
    command(project, [cmake, "--build", str(build)])
    suffix = ".exe" if os.name == "nt" else ""
    for test in ("test_core", "test_node", "test_sensors", "test_board_wifi"):
        command(project, [str(build / f"{test}{suffix}")])
    emitter = subprocess.run([str(build / f"emit_samples{suffix}")], cwd=project, capture_output=True, text=True, check=True)
    checker = subprocess.run([sys.executable, "tests/check_contract.py"], cwd=project, input=emitter.stdout, text=True, check=False)
    if checker.returncode:
        raise RuntimeError("the firmware serialiser produces payloads the published contract rejects")
    if shutil.which("idf.py"):
        command(project, ["idf.py", "build"])
    else:
        print("ARMOR_RADAR_FIRMWARE=NOT_BUILT ESP-IDF (idf.py) was not found; only the host-tested core was verified")


def test_solar(project: Path) -> None:
    """Build and run ARMOR-SOLAR's protocol library and node tests, then check the messages its serialiser and its ports print. Needs CMake and a C++17 compiler."""
    cmake = check_tool("cmake", "CMake and a C++17 compiler are required to test ARMOR-SOLAR (use Linux, WSL or MSYS2)")
    build = project / "build" / "host"
    command(project, [cmake, "-S", "tests", "-B", str(build), "-DCMAKE_BUILD_TYPE=Debug"])
    command(project, [cmake, "--build", str(build)])
    suffix = ".exe" if os.name == "nt" else ""
    for test in ("test_solar", "test_node", "test_board_eth"):
        command(project, [str(build / f"{test}{suffix}")])
    for emit in ("emit_samples", "emit_poller_samples"):
        emitter = subprocess.run([str(build / f"{emit}{suffix}")], cwd=project, capture_output=True, text=True, check=True)
        checker = subprocess.run([sys.executable, "tests/check_samples.py"], cwd=project, input=emitter.stdout, text=True, check=False)
        if checker.returncode:
            raise RuntimeError("the solar messages do not have the fields of contract version 0")


def test_electrical(project: Path) -> None:
    """Build and run ARMOR-ELECTRICAL's meter and switching tests, then check the messages its serialiser prints. Needs CMake and a C++17 compiler."""
    cmake = check_tool("cmake", "CMake and a C++17 compiler are required to test ARMOR-ELECTRICAL (use Linux, WSL or MSYS2)")
    build = project / "build" / "host"
    command(project, [cmake, "-S", "tests", "-B", str(build), "-DCMAKE_BUILD_TYPE=Debug"])
    command(project, [cmake, "--build", str(build)])
    suffix = ".exe" if os.name == "nt" else ""
    for test in ("test_meters", "test_interlock", "test_switch_set"):
        command(project, [str(build / f"{test}{suffix}")])
    emitter = subprocess.run([str(build / f"emit_samples{suffix}")], cwd=project, capture_output=True, text=True, check=True)
    checker = subprocess.run([sys.executable, "tests/check_samples.py"], cwd=project, input=emitter.stdout, text=True, check=False)
    if checker.returncode:
        raise RuntimeError("the electrical messages do not have the fields of contract version 0")


def validate_markdown_links(project: Path) -> None:
    missing: list[str] = []
    link = re.compile(r"\[[^]]+\]\(([^)]+)\)")
    for file in project.rglob("*.md"):
        for target in link.findall(file.read_text(encoding="utf-8")):
            target = target.split("#", 1)[0]
            if not target or "://" in target or target.startswith("mailto:"):
                continue
            if not (file.parent / target).resolve().is_file():
                missing.append(f"{file.relative_to(project)} -> {target}")
    if missing:
        raise RuntimeError("broken local Markdown links:\n" + "\n".join(missing))
    print("ARMOR_DOCS_LINKS=PASS")


def bump(project: Path, manifest: dict[str, object]) -> tuple[str, str]:
    before = str(manifest["version"])
    parts = before.split(".")
    if len(parts) != 3 or any(not part.isdigit() for part in parts):
        raise RuntimeError("manifest version must use major.minor.patch numeric format")
    # Odometer scheme: PATCH +1, rolling into MINOR past 9 (0.2.9 -> 0.3.0),
    # A previous version of this function stopped at 0.2.10 - a real
    # mistake found and corrected on ARMOR-SERVER's own 0.2.9 -> 0.2.10 bump.
    major, minor, patch = (int(part) for part in parts)
    patch += 1
    if patch > 9:
        patch = 0
        minor += 1
    after = f"{major}.{minor}.{patch}"
    manifest["version"] = after
    manifest["native_version"] = after
    manifest_path = project / "armor.project.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    # Android considers versionCode/versionName part of the install/update
    # identity.  Leaving Gradle at the old values after the shared manifest
    # bump creates an APK which Android quite correctly refuses as stale.
    # Keep this narrow to ARMOR's native client rather than guessing layouts
    # for every project that happens to contain a Gradle file.
    if manifest.get("name") == "ARMOR-ANDROID-CONTROL":
        gradle_file = project / "app" / "build.gradle.kts"
        if not gradle_file.is_file():
            raise RuntimeError("ARMOR-ANDROID-CONTROL is missing app/build.gradle.kts")
        gradle = gradle_file.read_text(encoding="utf-8")
        code_match = re.search(r"versionCode\s*=\s*(\d+)", gradle)
        name_match = re.search(r'versionName\s*=\s*"[^"]+"', gradle)
        if not code_match or not name_match:
            raise RuntimeError("ARMOR-ANDROID-CONTROL Gradle version fields are missing")
        gradle = gradle[:code_match.start(1)] + str(int(code_match.group(1)) + 1) + gradle[code_match.end(1):]
        gradle = re.sub(r'versionName\s*=\s*"[^"]+"', f'versionName = "{after}"', gradle, count=1)
        gradle_file.write_text(gradle, encoding="utf-8")
    # A Python project's own pyproject.toml `version` (PyPI-style packaging
    # identity) and its package `__init__.py`'s `__version__` mirror are a
    # separate copy of the number from armor.project.json's - found while
    # auditing the ecosystem: ARMOR-NETWORK's pyproject.toml stayed at 0.0.1
    # while its manifest reached 0.0.2, and ARMOR-COMMON's stayed at 0.2.3
    # against a manifest already at 0.2.6, unnoticed because nothing kept
    # them in sync. Kept narrow to the projects that actually have a
    # pyproject.toml (every PYTHON_PROJECTS/PYTEST_PROJECTS member).
    if manifest.get("name") in PYTHON_PROJECTS | PYTEST_PROJECTS:
        pyproject_file = project / "pyproject.toml"
        if pyproject_file.is_file():
            pyproject = pyproject_file.read_text(encoding="utf-8")
            pyproject, count = re.subn(r'(?m)^version\s*=\s*"[^"]+"', f'version = "{after}"', pyproject, count=1)
            if count:
                pyproject_file.write_text(pyproject, encoding="utf-8")
        for init_file in (project / "src").glob("*/__init__.py"):
            init_text = init_file.read_text(encoding="utf-8")
            init_text, count = re.subn(r'(?m)^__version__\s*=\s*"[^"]+"', f'__version__ = "{after}"', init_text, count=1)
            if count:
                init_file.write_text(init_text, encoding="utf-8")
    changelog = project / "CHANGELOG.md"
    previous = changelog.read_text(encoding="utf-8") if changelog.is_file() else "# Changelog\n\nAll notable changes to this project are documented here.\n"
    entry = f"\n## [{after}] - {date.today().isoformat()}\n\n- Verified build completed; release version advanced from `{before}` to `{after}`.\n"
    marker = "\n## "
    at = previous.find(marker)
    content = previous + entry if at < 0 else previous[:at] + entry + previous[at:]
    changelog.write_text(content.rstrip() + "\n", encoding="utf-8")
    return before, after


def run_project(project: Path, manifest: dict[str, object]) -> None:
    name = str(manifest["name"])
    environment = os.environ.copy()
    if name in PYTHON_PROJECTS:
        environment["PYTHONPATH"] = str(project / "src") + os.pathsep + environment.get("PYTHONPATH", "")
        module = {"ARMOR-SIMULATOR": "armor_simulator", "ARMOR-NETWORK": "armor_network", "ARMOR-SERVER-AI": "armor_server_ai.cli", "ARMOR-VOICE-AI": "armor_voice_ai.gateway"}.get(name)
        if not module:
            print("ARMOR-COMMON is a library; run its tests or consume it from another project.")
            return
        command(project, [sys.executable, "-m", module], environment)
    elif name == "ARMOR-STUDIO":
        check_tool("npm", "npm is required; install Node.js 22 or newer")
        # Keep Vite alive after this launcher returns.  On Windows, prefer an
        # installed Chromium browser's fullscreen mode; a web page itself is
        # not allowed to enter fullscreen without a user gesture.
        if os.name == "nt":
            flags = getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0) | getattr(subprocess, "CREATE_NO_WINDOW", 0)
            subprocess.Popen(["cmd.exe", "/d", "/c", NPM, "run", "dev"], cwd=project, creationflags=flags)
        else:
            subprocess.Popen([NPM, "run", "dev"], cwd=project)
        time.sleep(2)
        url = "http://127.0.0.1:5178"
        if os.name == "nt":
            browser = next((candidate for candidate in ("msedge.exe", "chrome.exe") if shutil.which(candidate)), None)
            if browser:
                subprocess.Popen([browser, "--start-fullscreen", url], creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
            else:
                webbrowser.open_new(url)
        else:
            webbrowser.open_new(url)
        print(f"ARMOR_STUDIO=LAUNCHED url={url} fullscreen_requested=True")
    elif name in NODE_PROJECTS:
        if name == "ARMOR-SERVER":
            environment = load_server_environment(project, environment)
        command(project, [NPM, "run", "dev"], environment)
    elif name == "ARMOR-DEVOPS":
        command(project, ["docker", "compose", "up", "--build"])
    elif name in {"ARMOR-RADAR", "ARMOR-ANDROID-CONTROL", "ARMOR-HARDWARE", "ARMOR-DOCS", "ARMOR-UPDATER"}:
        print(f"{name} has no safe generic runtime command. Use build-test to validate it, then follow its project documentation for hardware or IDE deployment.")
    else:
        raise RuntimeError(f"no run rule registered for {name}")


def main() -> int:
    parser = argparse.ArgumentParser(description="A.R.M.O.R. standardized project workflow")
    parser.add_argument("action", choices=("build", "build-test", "run"))
    parser.add_argument("project", type=Path)
    args = parser.parse_args()
    project = args.project.resolve()
    manifest_path = project / "armor.project.json"
    if not manifest_path.is_file():
        raise RuntimeError(f"manifest not found: {manifest_path}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("ecosystem") != "A.R.M.O.R.":
        raise RuntimeError("refusing non-A.R.M.O.R. manifest")
    print(f"PROJECT={manifest['name']} VERSION={manifest['version']} ACTION={args.action}")
    if args.action == "run":
        run_project(project, manifest)
        return 0
    test_project(project, manifest)
    if args.action == "build":
        before, after = bump(project, manifest)
        # The version change above must be compiled into the Android APK; a
        # second, incremental Gradle pass is what makes build.bat produce an
        # installable artifact whose version equals its manifest.
        if manifest.get("name") == "ARMOR-ANDROID-CONTROL":
            test_project(project, manifest)
        print(f"VERSION_BUMP=PASS v{before} -> v{after}")
    else:
        print("BUILD_TEST=PASS manifest and CHANGELOG unchanged")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (RuntimeError, json.JSONDecodeError) as error:
        print(f"ARMOR_WORKFLOW=FAIL {error}", file=sys.stderr)
        raise SystemExit(1)
